
api_login_check:
    path: /api/login_check
create_user:
    path: /api/v1/user
    controller: App\Controller\User\CreateUserController
    methods: [POST]
get_user:
    path: /api/v1/user/{id}
    controller: App\Controller\User\GetUserController
    methods: [GET]
update_user:
    path: /api/v1/user/{id}
    controller: App\Controller\User\UpdateUserController
    methods: [PUT]
search_user:
    path: /api/v1/users
    controller: App\Controller\User\SearchUserController
    methods: [GET]
delete_user:
    path: /api/v1/user/{id}
    controller: App\Controller\User\DeleteUserController
    methods: [DELETE]
