doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
        types:
            date: Bot\Infrastructure\Persistence\Doctrine\Dbal\Types\UTCDateType
            date_immutable: Bot\Infrastructure\Persistence\Doctrine\Dbal\Types\UTCDateImmutableType
            datetime: Bot\Infrastructure\Persistence\Doctrine\Dbal\Types\UTCDateTimeType
            datetime_immutable: Bot\Infrastructure\Persistence\Doctrine\Dbal\Types\UTCDateTimeImmutableType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Bot\Domain\Client\Model\Client:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/Client'
                prefix: 'Bot\Domain\Client\Model'
                alias: Bot\Domain\Client\Model\Client
            Bot\Domain\User\Model\User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/User'
                prefix: 'Bot\Domain\User\Model'
                alias: Bot\Domain\User\Model\User

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
